# Generated by Django 5.1.3 on 2025-05-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='university',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='education',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='faculty',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
