# Generated by Django 5.1.3 on 2024-12-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_created=True, verbose_name='Дата создания задачи')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.TextField(max_length=30, verbose_name='email')),
                ('message', models.TextField(max_length=400, verbose_name='Текстовое поле')),
            ],
        ),
    ]
